var members = {
    'Advisors': [
        {
            name: '張俊盛',
        },
    ],
    'Ph.D. Students': [
        {
            name: 'Joanne Boisson',
            alias: '喬安娜',
        },
    ],
    'Research Assistants': [
        {
            name: '彭皓鈞',
            alias: 'Henry',
        },
    ],
    'Master Students': [
        {
            name: '葉玫慈',
            alias: 'Mei-Chi',
            research: '相似詞',
            img: 'img/meichi.jpg',
            bkg_color: '#DC143C',
            intro: '碎碎念大嬸 - Mama Mama 別再唸我',
            link: 'https://youtu.be/z2Xsp0HMqf8',
        },
        {
            name: '陳怡君',
            alias: 'Yi-Chun',
            research: '機器翻譯、同步樣式文法',
            img: 'img/chun.jpg',
            bkg_color: '#EE7600',
            intro: '半夜睡不著覺，把心情哼成歌',
            link: 'https://youtu.be/O9cvAQEzG0o',
        },
        {
            name: '陳鵬宇',
            alias: 'Peng-Yu',
            research: '文法改錯',
            img: 'img/pengyu.jpg',
            bkg_color: '#CDCD00',
            intro: '太極拳法掌門人',
            link: 'https://youtu.be/wr-6wwt8RXk',
        },
        {
            name: '黃婕雅',
            alias: 'jr',
            research: '相似詞',
            img: 'img/jr.jpg',
            bkg_color: '#008B45',
            intro: '只是你遲到一千年！',
            link: 'https://youtu.be/83TjxZWFXVI',
        },
        {
            name: '陳志杰',
            alias: 'jjc',
            research: '文法改錯、機器翻譯、同步樣式文法',
            img: 'img/jjc.jpg',
            bkg_color: '#36648B',
            intro: '我是胖虎，我是孩子王',
            link: 'https://youtu.be/Y-gGTPsLORY',
        },
        {
            name: '吳瑀瑄',
            alias: 'shanny',
            research: '動詞偵錯與改錯',
            img: 'img/shanny.jpg',
            bkg_color: '#473C8B',
            intro: '看到我請提醒我記得收電源線（づ¯ ³ ¯）づ',
            link: 'https://youtu.be/HhN3hv2CVbA',
        },
        {
            name: '吳奇恩',
            alias: '87n',
            research: '自然語言處理、同義詞',
            img: 'img/57n.jpg',
            bkg_color: '#141414',
            intro: '白痴',
            link: 'https://youtu.be/hgGFe4eJ0qc',
        },
        {
            name: '杜惟真',
            alias: 'Jane',
            research: '自然語言處理',
            img: 'img/jane.jpg',
            bkg_color: '#EEAD0E',
            intro: '呵呵呵',
            link: 'https://youtu.be/7sbKm-hAlsw',
        },
    ],
    'Undergraduates': [
        {
            name: '朱凰華',
            alias: 'Garnix',
            research: 'Email寫作輔助',
        },
        {
            name: '徐芷琳',
            alias: 'Chih-Lin',
            research: 'Email寫作輔助',
        },
        {
            name: '簡紹安',
            alias: 'Shao-An',
            research: '自然語言搜尋介面',
        },
        {
            name: '蔡明勳',
            alias: 'Frank',
            research: '自然語言搜尋介面',
        },
    ],
};